# [File: scripts/dbc_codegen.py]
import re
import os

def generate_cpp_code(dbc_path, output_hpp):
    print(f"Parsing {dbc_path}...")
    
    # D8 核心正则武器
    bo_regex = re.compile(r'^BO_\s+(\d+)\s+(\w+):\s+(\d+)\s+(\w+)')
    # 💡 升级后的三合一 sg_regex 正则武器！
    # 核心改动：在信号名 (\w+) 后面，增加了可选的分组 (M|m\d+)? 来捕获多路复用标记
    sg_regex = re.compile(
        r'^\s+SG_\s+(\w+)\s*(M|m\d+)?\s*:\s*(\d+)\|(\d+)@([01])([+-])\s*\(([^,]+),([^)]+)\)\s*\[([^|]+)\|([^\]]+)\]\s*"([^"]*)"'
    )

    messages = []
    current_msg = None

    # 1. 词法扫描 DBC 文件
    with open(dbc_path, 'r', encoding='utf-8') as f:
        for line in f:
            # 匹配报文 BO_
            bo_match = bo_regex.match(line)
            if bo_match:
                current_msg = {
                    'id': bo_match.group(1),
                    'name': bo_match.group(2),
                    'dlc': bo_match.group(3),
                    'signals': []
                }
                messages.append(current_msg)
                continue
            
            # 匹配信号 SG_
            sg_match = sg_regex.match(line)
            if sg_match and current_msg is not None:
                mux_indicator = sg_match.group(2) # 这里可能抓到 'M', 'm0', 'm1' 或者 None
                
                # 💡 初始化多路复用的这三个新字段
                is_multiplexor = 'false'
                is_multiplexed = 'false'
                mux_value = -1
                
                if mux_indicator == 'M':
                    is_multiplexor = 'true'
                elif mux_indicator and mux_indicator.startswith('m'):
                    is_multiplexed = 'true'
                    mux_value = int(mux_indicator[1:]) # 提取出 m1 中的数字 1

                current_msg['signals'].append({
                    'name': sg_match.group(1),
                    'is_multiplexor': is_multiplexor,
                    'is_multiplexed': is_multiplexed,
                    'mux_value': mux_value,
                    'start_bit': sg_match.group(3),
                    'length': sg_match.group(4),
                    'is_be': 'true' if sg_match.group(5) == '0' else 'false', # 0是大端
                    'is_signed': 'true' if sg_match.group(6) == '-' else 'false', # -是有符号
                    'factor': sg_match.group(7),
                    'offset': sg_match.group(8)
                })

    # 2. 动态渲染/生成 C++ 头文件源码
    hpp_content = """// =================================================================
// ⚠️  AUTOMATICALLY GENERATED FILE - DO NOT EDIT BY HAND
// Generated by dbc_codegen.py
// =================================================================

#ifndef GENERATED_CAN_NETWORK_HPP
#define GENERATED_CAN_NETWORK_HPP

#include "can_parser.hpp"

inline void init_generated_database(CanParser& parser) {
    // 自动启用白名单模式，确保只有注册的ID会被解析
    parser.enableWhitelist(true);
    
    // 自动添加所有DBC中定义的ID到白名单
"""

    # 收集所有唯一的ID
    unique_ids = set()
    for msg in messages:
        unique_ids.add(int(msg['id']))

    # 生成白名单添加代码
    for msg_id in sorted(unique_ids):
        msg_name = next((msg['name'] for msg in messages if int(msg['id']) == msg_id), f"ID_{msg_id}")
        hpp_content += f"    parser.addToWhitelist({msg_id}); // {msg_name}\n"
    
    hpp_content += "\n    // 信号注册\n"

    for msg in messages:
        hpp_content += f"    // 报文注册: {msg['name']} (ID: 0x{int(msg['id']):X})\n"
        for sg in msg['signals']:
            
            dbc_start_bit = int(sg['start_bit'])
            if sg['is_be'] == 'true': # 如果是大端 (@0)
                # 💡 终极对齐公式：直接计算该大端信号在整个 8 字节中，顺向数过去的起始比特位
                byte_num = dbc_start_bit // 8
                bit_in_byte = dbc_start_bit % 8
                # 针对你的算法：输入 7 (Byte0, bit7) -> 应该输出 0
                final_start_bit = byte_num * 8 + (7 - bit_in_byte)
            else:
                final_start_bit = dbc_start_bit

            hpp_content += (
                f"    parser.registerSignal({msg['id']}, "
                f"Signal(\"{sg['name']}\", {final_start_bit}, {sg['length']}, {sg['is_be']}, {sg['is_signed']}, "
                f"{sg['factor']}, {sg['offset']}, {sg['is_multiplexor']}, {sg['is_multiplexed']}, {sg['mux_value']}));\n"
            )
        hpp_content += "\n"

    hpp_content += """}

#endif // GENERATED_CAN_NETWORK_HPP
"""

    # 3. 写入输出文件
    os.makedirs(os.path.dirname(output_hpp), exist_ok=True)
    with open(output_hpp, 'w', encoding='utf-8') as f:
        f.write(hpp_content)
    
    print(f"🎉 Success! Generated {output_hpp} with {len(messages)} messages.")

if __name__ == "__main__":
    # 执行生成
    generate_cpp_code("protocol/test_matrix.dbc", "include/generated_can_network.hpp")